### ISSUE TITLE
milgram-pod launchers may be failing to correctly filter their spawnee's deaths.

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#151]
At this point maybe we should consider putting this stuff in some sort of base behavior delegate class; we've fixed this on the anthills, and it's probably the same issue here.

**Comment by rkettering** [comment]
Anything that uses the mechanism of storing object references locally, and then checking the referred objects, is going to be broken - at least if the objects are swallowable, because the new semantics on that destroy the previous object.  We need to change every object that tracks spawnees.

We've created a new FFL class to standardize this behavior.

**We need to fix it on:**
- [x] anthill
- [x] milgram_pod_launcher
- [ ] milgram_block_spawner
- [ ] maggot_white_controller
- [ ] maggot_grey_controller
- [ ] moth_boss
- [ ] mushroom_jellyfish_spawner
- [ ] periodic_spawning_enemy_generator
 
**TODO:  make sure this list is comprehensive**
